### ISSUE TITLE
camera after usb cable extension not working

### ISSUE THREAD

**Issue by frozenowni** [3DO-EU/nozzle-camera#10]
Hello,
I'm working on my voron 2.4 with stealthburner toolhead. Unfortunately i only ordered the usb cable in 1 m length, which is way too short for my 350³ build... (needs >= 2.5 m)
I provisionally installed the HD version of the nozzle cam using the original usb cable and was happy that it worked there.
After that i cut the usb cable and inserted 2 m of cable between the original plug and the camera side cable (soldered cables and checked continuity)
Unfortunately now the camera is not working anymore.

The situation is:
- camera shows up on lsusb
- camera does not show up in ls /dev/video*
- camera does not show up in dmesg | grep Webcam

I don't get, where the error might be. Thought this might be a problem others stumble accross so decided to report as an issue.

Thx in advance and BR

**Comment by thbl** [comment]
the issue is no cable length as ours 3.5m works fine.
It's really hard to say what it is without the PCB in hand, but defiantly hardware related.

**Comment by frozenowni** [comment]
Hi,
Thanks for the reply. I'm gonna order the appropriate length. However in the meantime I'd like to make one myself.
Is there a pinout for the adapter board?
