### ISSUE TITLE
Stealthburner PCB Mount? 

### ISSUE THREAD

**Issue by bradtn** [3DO-EU/nozzle-camera#17]
I know there's a ADXL mount but it's kind of a little ugly for my tastes. The back of my stepper also isn't available for the 3do pcb as I have a canbus board. I am wondering if someone more skilled than I could create a mount for the inside of the stealth burner where normally the pcb would be mounted as I won't be using said mount that would be the most ideal enclosed location?

**Comment by thbl** [comment]
see https://github.com/3DO-EU/nozzle-camera/tree/main/printers/Voron_Stealthburner/Cam_mount_SB%20mod%20by%20Panzarkatten

**Comment by thbl** [comment]
see https://github.com/3DO-EU/nozzle-camera/tree/main/printers/Voron_Stealthburner/Cam_mount_SB%20mod%20by%20Panzarkatten

**Comment by testack18** [comment]
Why is this thread closed? That link does not really a mount. Its just some fancy face for the SB and a bit of cutout for the USB cable. There is no proper mount option for the PCB inside the toolhead like the topic opener asked. 

Also the main body of the SB toolhead modification is not a well designed. I tried to push the fu...ng ribbon cable into it while trying to avoid putting it into the path of the airflow. Its hard to push the cable into the channels without damaging it. The whole design should re-think or have an official statement that it is not supported to put it and mount it within the toolhead.
