### ISSUE TITLE
Connecting the LEDs

### ISSUE THREAD

**Issue by Siiggyy** [3DO-EU/nozzle-camera#19]
Could someone explain to me how i would need to connect the LEDs to some sort of power what would be the best option?

**Comment by Mattang-Tim** [comment]
The LED configuration and setup can be found in the stealthburner repo.

**Comment by Siiggyy** [comment]
Thanks for your answer but unfortunately this did not help me since i do not own a stealthburner. I found a workaround with a ocotoprint plugin but it's not optimal. Is there another option to get it running over a raspberry pi running octoprint?
