### ISSUE TITLE
Useless fixed focal length

### ISSUE THREAD

**Issue by Kaelum** [3DO-EU/nozzle-camera#28]
Unless you are able to mount this at the EXACT distance away from the nozzle tip, good luck in using it.  The lens cannot be adjusted, so don't waste your time, or money, trying.

**Comment by jonyo** [comment]
The docs mentioned it is fixed with glue and if you adjust it, they say to add glue replacement... I'm guessing you had trouble removing the existing glue? What kind of glue was it, just hot glue or what @Kaelum ?

**Comment by Kaelum** [comment]
The glue appears to be some kind of CA glue, which you can break free, but you will seriously deform the plastic in doing so.  If there are any threads, the threads will be destroyed too, as I don't see any threads at all.  They made some seriously bad choices in creating this, and not providing an adjustment tool is just plain stupid on their part.  This product is not ready for sale.
