### ISSUE TITLE
USB cable from camera to Raspberry PI 

### ISSUE THREAD

**Issue by z00mantwo** [3DO-EU/nozzle-camera#3]
Can I just run four 24awg Linneo 40 stand wires from the camera controller board in the tool head to a solder on USB connector at the PI? Or is a larger wire needed? Possibly 20awg? 

Also what is the connector type at the camera board? Looks like a 5 conductor connector of some type.

**Comment by thbl** [comment]
it a normal usb 2.0 cable, using a 5pin connecter with 1,0mm pitch
