### ISSUE TITLE
3D model of IMX258 camera

### ISSUE THREAD

**Issue by arsi-apli** [3DO-EU/nozzle-camera#4]
I made a simple 3D model of the IMX258 camera. I also added a focus window, for a resolution of 800x600 and a focus length of 32mm from the back of the camera. I tried to measure it today and the sharpest image comes out at that 32mm.
https://cad.onshape.com/documents/fd0fddae3badd59be00c2c5a/w/82d33f3f9ffa0c6dbaafe43e/e/5e3cb29dfecb02d187eca4b2?renderMode=0&uiState=63e7aa22ee9848108c0e9bb3

And I'm starting to work on my version for Hemera XS+ 3D printed Hermit CRAB + CPAP blower
https://cad.onshape.com/documents/c995be608a88407895310cc1/w/17480634f20bc058e5809fa7/e/f379a3a739f7b14b5432ae84?renderMode=0&uiState=63e8c3793053f222bde150db

btw, what is the best camera angle?

**Comment by thbl** [comment]
*Focus distance from the back side of the camera to the object is set to 34.5mm
