### ISSUE TITLE
Request: mounting for Bambu Lab X1

### ISSUE THREAD

**Issue by chaugan** [3DO-EU/nozzle-camera#5]
I hope someone is able to create a mounting for the Bambu Lab X1!

**Comment by chuckkay** [comment]
Im hoping for a mount as well and hopefully someone figures a way to use the existing USB-C cable in the Bambu x1 Hotend housing (like with a splitter)

**Comment by chaugan** [comment]
@thbl was the support for Bambu Lab dropped or added?
