### ISSUE TITLE
Nozzle cam board and sb2040

### ISSUE THREAD

**Issue by 33martin** [3DO-EU/nozzle-camera#6]
is it possible to use the nozzlecam board and the sb2240 can board together (is there enough space behind the fan)

**Comment by thbl** [comment]
There should be enough space behind the stepper motor

**Comment by 33martin** [comment]
@whi-tw this is exactly what i mean.....

**Comment by arekm** [comment]
Was considering this nozzle cam but looks like this issue is not solved (and even ignored). Please reopen.
