### ISSUE TITLE
H.264 Encoding

### ISSUE THREAD

**Issue by whi-tw** [3DO-EU/nozzle-camera#7]
Hullo,

Is there anything in the works to either enable H.264 encoding on the existing encoder board (unsure if this is possible?) or to put out a board that does support H.264?

MJPG is great if you have a GPU / hardware MJPG encoding available, but 3D printer webcams are predominantly connected to arm(64) SBCs which have hardware H.264 encoding, but dealing with MJPG is painful.

Context: I've bought a 4K webcam, capable of 1080p60, but because of the heft of the MJPG stream, I'm barely able to stream the feed at ~20 fps consistently!

Thanks,

Tom

**Comment by thbl** [comment]
@whi-tw well it depends on your hardware, if you use a PC instead of a pi to stream you probably will get better results.
But there is a h264 / webrtc for Rpi in the works, will be released when we are ready ! ;)
