### ISSUE TITLE
Voron 2.4 - Are we to route the supplied USB cable through the gantry cable chain?

### ISSUE THREAD

**Issue by RudyAlbertoAcostaMarmalade** [3DO-EU/nozzle-camera#8]
Quick question - the supplied USB cable is quite 'chunky', is the expectation for Voron users to route the cable into and through the existing Voron gantry cable chains? If so, due to it's size I cannot help but think this would have detrimental impact on the movement of the chains, which may subsequently impact printing/quality. Can you please confirm if this is the case?

Or, are we meant to remove the a majority of the USB cable's outer sheath exposing the five inner cables and route those through the Voron Gantry cable chain, if so, are the inner wires of the supplied USB cable Heflon/Teflon based so that they can withstand the repeated movements?

Thanks in advance.

**Comment by thbl** [comment]
most peopel now days use umbrella mod, that said we have used it without problems in cables chains.
We do not recommend to remove the outer shell of USB cable, as its protects cable aginst bend,heat, and EMI

**Comment by RudyAlbertoAcostaMarmalade** [comment]
Good to know - Thanks for the response.

**Comment by grzbiet** [comment]
> most peopel now days use umbrella mod
what's the umbrella mod, seems I can't google anything like that related to voron or even any 3d printer...

**Comment by fryc88** [comment]
Probably they mean umbilical mod ;)
